version: '2.0'
services:
#PHP Service
# The existing database container configuration...
  php-apache:
    container_name: php-apache
    build:
      context: .
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      # - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db_mysql
    networks:
      backend:
          ipv4_address: 192.168.1.4
#database services
  db_mysql:
      image: mysql:8-oracle
      container_name: cont_db_mysql
      restart: always 
      env_file:
      - ./.env
      networks:
        backend:
          ipv4_address: 192.168.1.2
      expose:
        - ${DB_PORT}   
      ports: 
        - ${DB_PORT}:${DB_PORT}
      volumes:  
        - ./db/data/:/var/lib/mysql/ 
        - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        MYSQL_PASSWORD: $DB_PASSWORD
        MYSQL_USER: $DB_USERNAME
        MYSQL_DATABASE: $DB_DATABASE 
        MYSQL_ROOT_PASSWORD: $DB_PASSWORD

#Docker Networks
networks:
  frontend:
    # Use a custom driver
    driver: bridge
  backend: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/20
          gateway: 192.168.1.1
#Volumes
volumes:
  dbdata:
    driver: local